- example/README.md
- tests/test_cli.py
- unidep/_cli.py
Closes https://github.com/basnijholt/unidep/issues/52
> Install local and include dependencies in a single shot

- README.md
- tests/test_unidep.py
- tests/test_version_conflicts.py
- unidep/_conflicts.py
> Only check if multiple pinnings are different and document pinnings

- .github/release.py
- README.md
- example/pyproject_toml_project/pyproject.toml
- example/setup_py_project/requirements.yaml
- example/setuptools_project/requirements.yaml
- tests/simple_monorepo/common-requirements.yaml
- tests/simple_monorepo/project1/requirements.yaml
- tests/simple_monorepo/project2/requirements.yaml
- tests/test_cli.py
- tests/test_parse_yaml_includes.py
- unidep/__init__.py
- unidep/_cli.py
- unidep/_dependencies_parsing.py
- unidep/_pytest_plugin.py
Closes #105
----
📚 Documentation preview 📚: https://unidep--109.org.readthedocs.build/en/109/
> Rename `includes` to `local_dependencies`

- docs/source/conf.py
----
📚 Documentation preview 📚: https://unidep--112.org.readthedocs.build/en/112/
> Use webp logo

- example/README.md
- unidep/_dependencies_parsing.py
----
📚 Documentation preview 📚: https://unidep--114.org.readthedocs.build/en/114/
> Local dependencies minor cleanup

- README.md
- docs/source/FAQ.md
- docs/source/index.md
> Adding FAQ questions to README

- README.md
----
📚 Documentation preview 📚: https://unidep--117.org.readthedocs.build/en/117/
> Add example for non UniDep managed dependency

- README.md
- docs/source/.gitignore
- docs/source/conf.py
- docs/source/index.md
----
📚 Documentation preview 📚: https://unidep--118.org.readthedocs.build/en/118/
> Fix anchor links in documentation

- docs/source/conf.py
- pyproject.toml
----
📚 Documentation preview 📚: https://unidep--119.org.readthedocs.build/en/119/
> Enable Ruff for docs/source/conf.py

- docs/Makefile
- docs/source/.gitignore
- docs/source/conf.py
- docs/source/index.md
----
📚 Documentation preview 📚: https://unidep--120.org.readthedocs.build/en/120/
> Set names for the auto generated docs pages

- README.md
----
📚 Documentation preview 📚: https://unidep--125.org.readthedocs.build/en/125/
> Rephrase some introduction phrases

- README.md
> Answer 2 more FAQs

- example/hatch2_project/README.md
----
📚 Documentation preview 📚: https://unidep--127.org.readthedocs.build/en/127/
> Fix example in `example/hatch2_project/README.md`

- tests/test_utils.py
- unidep/_setuptools_integration.py
- unidep/platform_definitions.py
- unidep/utils.py
----
📚 Documentation preview 📚: https://unidep--133.org.readthedocs.build/en/133/
> Always prevent `UnsupportedPlatformError` during installation

- README.md
----
📚 Documentation preview 📚: https://unidep--135.org.readthedocs.build/en/135/
> Add "UniDep in the Wild" example in FAQ

- unidep/_conda_lock.py
----
📚 Documentation preview 📚: https://unidep--140.org.readthedocs.build/en/140/
> Do not set platforms in `conda_lock_command`

- unidep/_pytest_plugin.py
----
📚 Documentation preview 📚: https://unidep--141.org.readthedocs.build/en/141/
> Improvements to the undocumented pytest plugin

- README.md
- tests/test_cli.py
- unidep/_cli.py
----
📚 Documentation preview 📚: https://unidep--142.org.readthedocs.build/en/142/
> Allow installing into a different environment

- .github/workflows/pytest.yml
- tests/test_cli.py
- tests/test_parse_yaml_local_dependencies.py
- unidep/_cli.py
----
📚 Documentation preview 📚: https://unidep--143.org.readthedocs.build/en/143/
> Run tests on Windows and MacOS

- tests/test_conda_lock.py
- unidep/_conda_lock.py
cc @fbuessen
----
📚 Documentation preview 📚: https://unidep--146.org.readthedocs.build/en/146/
> Fix conda-lock generation for packages with circular dependencies

- .pre-commit-config.yaml
- pyproject.toml
- tests/test_cli.py
- unidep/_cli.py
- unidep/_setuptools_integration.py
- unidep/utils.py
----
📚 Documentation preview 📚: https://unidep--148.org.readthedocs.build/en/148/
> Print more package information with `unidep version`

- README.md
- tests/test_conda_lock.py
- unidep/_cli.py
- unidep/_conda_lock.py
----
📚 Documentation preview 📚: https://unidep--149.org.readthedocs.build/en/149/
> Allow passing through arguments to conda-lock

- README.md
- example/README.md
- example/hatch_project/pyproject.toml
- example/hatch_project/requirements.yaml
- example/pyproject_toml_project/pyproject.toml
- example/setuptools_project/pyproject.toml
- example/setuptools_project/requirements.yaml
- pyproject.toml
- tests/test_cli.py
- tests/test_unidep.py
- tests/test_utils.py
- unidep/_cli.py
- unidep/_conflicts.py
- unidep/_dependencies_parsing.py
- unidep/_hatch_integration.py
- unidep/_setuptools_integration.py
- unidep/utils.py
TODO:
----
📚 Documentation preview 📚: https://unidep--134.org.readthedocs.build/en/134/
> Allow optional-dependencies for both Conda and pip

- example/README.md
- tests/test_unidep.py
- unidep/_dependencies_parsing.py
----
📚 Documentation preview 📚: https://unidep--151.org.readthedocs.build/en/151/
> Fix issue where dep is dict in `optional_dependencies`

- README.md
----
📚 Documentation preview 📚: https://unidep--156.org.readthedocs.build/en/156/
> Change order in example requirements

- unidep/utils.py
----
📚 Documentation preview 📚: https://unidep--164.org.readthedocs.build/en/164/
> Use tomllib or toml when available

- tests/test_parse_yaml_local_dependencies.py
- unidep/_dependencies_parsing.py
----
📚 Documentation preview 📚: https://unidep--163.org.readthedocs.build/en/163/
> Fix case where local dependencies aren't correctly installed

- README.md
----
📚 Documentation preview 📚: https://unidep--172.org.readthedocs.build/en/172/
> Add pipx instructions

- .github/workflows/install-example-projects.yml
- example/environment.yaml
- example/pyproject_toml_project/pyproject.toml
- example/setup_py_project/requirements.yaml
- example/setuptools_project/requirements.yaml
----
📚 Documentation preview 📚: https://unidep--178.org.readthedocs.build/en/178/
> Fix installation of example projects in CI

- README.md
- example/README.md
- pyproject.toml
- tests/test_cli.py
- tests/test_cli_install_conda_lock.py
- unidep/_cli.py
----
📚 Documentation preview 📚: https://unidep--183.org.readthedocs.build/en/183/
> Add the option to install from a conda-lock file in one go

- tests/test_parse_yaml_local_dependencies.py
- unidep/_dependencies_parsing.py
----
📚 Documentation preview 📚: https://unidep--190.org.readthedocs.build/en/190/
> ENH: Add check for empty Git submodules

- README.md
Based on https://github.com/epogrebnyak/justpath/issues/26#issuecomment-2041556267.
----
📚 Documentation preview 📚: https://unidep--191.org.readthedocs.build/en/191/
> Add Python Bytes badge

- .github/renovate.json
- example/README.md
----
📚 Documentation preview 📚: https://unidep--197.org.readthedocs.build/en/197/
> Add Renovate CI

- tests/test_local_wheels_and_zip.py
- unidep/_dependencies_parsing.py
Closes https://github.com/basnijholt/unidep/issues/211.
----
📚 Documentation preview 📚: https://unidep--212.org.readthedocs.build/en/212/
> Allow installing `.whl` and `.zip` in `local_dependencies`

- README.md
- example/README.md
- example/environment.yaml
- tests/test_cli.py
- unidep/_cli.py
- unidep/_dependencies_parsing.py
----
📚 Documentation preview 📚: https://unidep--215.org.readthedocs.build/en/215/
> Use `uv` by default when pip installing

- unidep/_dependencies_parsing.py
----
📚 Documentation preview 📚: https://unidep--216.org.readthedocs.build/en/216/
> Check for empty folders and raise with better error message

- unidep/_cli.py
----
📚 Documentation preview 📚: https://unidep--218.org.readthedocs.build/en/218/
> Still do `conda run` for `uv`

- README.md
- unidep/_cli.py
----
📚 Documentation preview 📚: https://unidep--219.org.readthedocs.build/en/219/
> Add `-n` alias for `--conda-env-name`

- unidep/_cli.py
----
📚 Documentation preview 📚: https://unidep--220.org.readthedocs.build/en/220/
> Print the total time to install (now that it is fast ⚡)

- README.md
- bootstrap.sh
----
📚 Documentation preview 📚: https://unidep--226.org.readthedocs.build/en/226/
> Add bootstrap.sh script

- bootstrap.sh
----
📚 Documentation preview 📚: https://unidep--227.org.readthedocs.build/en/227/
> Update bootstrap.sh to install unidep[all]

- README.md
----
📚 Documentation preview 📚: https://unidep--228.org.readthedocs.build/en/228/
> Rename "Quickstart" to "Bootstrap from Scratch"

- unidep/_conda_lock.py
----
📚 Documentation preview 📚: https://unidep--241.org.readthedocs.build/en/241/
> Sort dependencies in sublock files

- bootstrap.sh
Seems to work now https://github.com/mamba-org/mamba/issues/3740#issuecomment-2749401730
> Don't restrict micromamba 1.5.12-0 bootstrap.sh
